build.gradle
=> Updated PathPlannerLib to latest and WPILib to 2023.2.1

src/main/java/frc/robot/Constants.java
new jetski cancoder offsets after supergluing the magnet in
=> Fix CANCoder offset 

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/commands/TestTransform.java, src/main/java/frc/robot/subsystems/Swerve.java
Updated new april tag constants.
=> Updated constant

build.gradle
Closes #45 
If we wanted to test this, I'm not sure how since there is no robot to test on for this year.
=> Update robot version to 2023.3.2

README.md, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java
Updated CAN ids and fixed LED constants.
=> Assign can ids

README.md
=> Adjusted can ids

build.gradle, vendordeps/PathplannerLib.json, vendordeps/Phoenix.json, vendordeps/REVLib.json, vendordeps/photonlib.json
=> Update to WPIlib 2023.4.1

src/main/java/frc/robot/RobotContainer.java
=> Removed digital input from robot containers leds

src/main/java/frc/lib/util/Scoring.java, src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/RobotContainer.java
Need to tune arm/wrist position for intaking from single substation.
=> new intake position

src/main/java/frc/lib/util/Scoring.java, src/main/java/frc/robot/RobotContainer.java
Added operator confirmation to auto commands.
=> Move to score confirmation

src/main/java/frc/lib/util/Scoring.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/arm/ArmIntake.java
Changed widgets, positions, and auto.
=> Adjustments

vendordeps/PathplannerLib.json, vendordeps/Phoenix.json, vendordeps/photonlib.json
=> Update Vendor Deps to Latest Version

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/arm/ConeIntake.java, src/main/java/frc/robot/commands/arm/CubeIntake.java, src/main/java/frc/robot/commands/arm/DockArm.java, src/main/java/frc/robot/subsystems/Arm.java
Intake tuned, ground intake positions made.
=> New intake

src/main/java/frc/lib/util/PhotonCameraWrapper.java, src/main/java/frc/robot/subsystems/Swerve.java
Based on recent Photonvision updates to their examples:
- [Example Drivetrain Code](https://github.com/PhotonVision/photonvision/blob/master/photonlib-java-examples/apriltagExample/src/main/java/frc/robot/Drivetrain.java#L180)
- [Example PhotonCamera Code](https://github.com/PhotonVision/photonvision/blob/master/photonlib-java-examples/apriltagExample/src/main/java/frc/robot/PhotonCameraWrapper.java)
Need to test:
=> New Apriltag Method

src/main/java/frc/lib/util/Scoring.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/arm/ConeIntake.java, src/main/java/frc/robot/commands/arm/CubeIntake.java, src/main/java/frc/robot/subsystems/WristIntake.java
- Fixed scoring positions
- Fixed intake positions
- Inverts intake on cube or cone
=> Quality of Life Updates

src/main/java/frc/lib/util/PhotonCameraWrapper.java, src/main/java/frc/lib/util/Scoring.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/autos/Score1Dock.java, src/main/java/frc/robot/commands/wrist/WristIntakeRelease.java, src/main/java/frc/robot/subsystems/Arm.java, src/main/java/frc/robot/subsystems/Swerve.java
closes #153 
- Fixed positions
- April tag positions
- Added outtake button
=> Fixed Auto Align and Arm Position

src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/autos/CrossAndDock.java, src/main/java/frc/robot/autos/LeaveCommunity.java, src/main/java/frc/robot/commands/drive/TurnToAngle.java
Robot now faces the right direction when leaving community.
=> Turn 180 after leaving community

src/main/java/frc/lib/util/PhotonCameraWrapper.java, src/main/java/frc/lib/util/Scoring.java, src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/commands/arm/ConeIntake.java, src/main/java/frc/robot/commands/arm/ConeUpIntake.java, src/main/java/frc/robot/commands/arm/CubeIntake.java, src/main/java/frc/robot/subsystems/Swerve.java
- Changed aligning
- Changed widgets
- Added new cone intake 
- Increased angular velocity
closes #157, #138
=> Robot changes

src/main/java/frc/robot/RobotContainer.java
Made cone intake from top x
Made cone from floor b
Made cube intake a
=> Changed buttons

src/main/java/frc/robot/Constants.java, src/main/java/frc/robot/Robot.java, src/main/java/frc/robot/RobotContainer.java, src/main/java/frc/robot/subsystems/Arm.java
Touch sensor to change brake mode to coast mode while disabled.
=> Coast to Brake mode sensor
